### ISSUE TITLE
Package not loading in 0.172.0

### ISSUE THREAD

**Issue by johnwayne087** [skandasoft/preview-plus#1]
I just installed this amazing looking atom package but I cant seem to get it to work at all in the latest version of Atom (0.172.0). I included two screen shots, one of the packages I also have installed and one of the main interface. 
![1](https://cloud.githubusercontent.com/assets/1955197/5746348/d5faac9a-9be3-11e4-9744-0e59e91a84cb.JPG)
![2](https://cloud.githubusercontent.com/assets/1955197/5746350/d79b0112-9be3-11e4-8ec6-582d09135853.JPG)

**Comment by johnwayne087** [comment]
After finally getting the node.js modules installed that i was missing (theorist, htmltojsx) it seems to be working. The only issue i have now is that when I use Live Preview of HTML it doesn't seem to parse my CSS page.

**Comment by skandasoft** [comment]
fixed. Please check the latest version. Just to understand, did the htmltojx not get downloaded along with the module since it is part of bundledDependencies

**Comment by johnwayne087** [comment]
No htmltojsx was not installed, in a long roundabout way i was able to get installed manually.

**Comment by skandasoft** [comment]
I have an updated version. I am closing assuming the new version took care of fixes. Please feel free to reopen/open new issues.
