### ISSUE TITLE
Deprecated calls

### ISSUE THREAD

**Issue by fibric** [skandasoft/preview-plus#22]
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: **https://atom.io/docs/api/latest/Workspace**. If you do need the view, please use **atom.views.getView(atom.workspace)**, which returns an HTMLElement.

Called 1 time **Create Issue on preview-plus repo**
```javascript
Atom.Object.defineProperty.get - /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/atom.js:54:11
<unknown> - /Users/fibric/.atom/packages/preview-plus/lib/preview-plus.coffee:48:25
```

**Comment by skandasoft** [comment]
This is on my list of todo things...right now I am concentration on optimization and features...will certainly get to it.

**Comment by skandasoft** [comment]
Taken Care
