### ISSUE TITLE
preview~* files are not removed

### ISSUE THREAD

**Issue by olmokramer** [skandasoft/preview-plus#3]
The `preview~*` file that is created is not removed after closing the preview. I'm on Atom 0.176.0 on Linux Debian 8

**Comment by skandasoft** [comment]
Can you please provide more information. Which file /compileTo were you using..

**Comment by olmokramer** [comment]
It's any file I tried, which is: `.coffee`, `.less`, `.styl`, `.md`, `.jade` (which didn't compile, but the resulting `.err` was not removed) all compiled to the default for that file type

**Comment by skandasoft** [comment]
I have tested this using windows. But how does the npm executable work in linux. The Preview-plus is calling the npm executable say in case of coffeescript it would call coffee followed by the input /output file. so my question is, for Linux what will be executable name/ does it end with extension(bat/exe as in case of windows) or should be called with sudo(for admin in the prefix). I think that is what is happening is calling these executable fails.. 
Thanks for the feedback.

**Comment by olmokramer** [comment]
Npm binaries don't have an extension on linux and don't have to be called with sudo, npm symlinks them in `/usr/bin` which is in the `$PATH`, so no need to run with `sudo`.  So to compile coffeescript you'd just run `coffee -c <input file> -o <output dir>` from the terminal. But compilation is not the problem (except in the case of `.jade` files), it's that the temporary `preview~...` files are not deleted after closing the preview pane.

So when I preview `test.coffee`, a file `preview~test.coffee.js` is created in the root of my project, but when I close the preview tab/pane, the `preview~test.coffee.js` file remains there. I would expect it to be deleted when I'm done previewing

**Comment by skandasoft** [comment]
I am not saving the compiled file. In the Readme I had mentioned about save while exiting may that would have saved the file. For now click on cancel while you quit atom. 
By the way on Jade is it compiling. It is also npm module. so I am expecting it should be problem. Can  you please share the issues on the compilation for jade.

**Comment by olmokramer** [comment]
Ahh. I see. It was the `autosave` core package that was causing the problems... It automatically saved the newly created tab when it lost focus... Is there a way to turn off autosave for a specific tab?
I'll close this issue and open another one for the jade compilation.

**Comment by skandasoft** [comment]
I don't have the autosave switched on. I will check that put the fix for as I find time. Thanks

**Comment by olmokramer** [comment]
Thanks! I see I closed this issue, but I'll reopen it because you are going to look for a solution.

**Comment by skandasoft** [comment]
Is there a way to disable autosave at the item level..that you are aware of..

**Comment by olmokramer** [comment]
No I'm sorry. I don't know anything about the autosave package :(

**Comment by skandasoft** [comment]
Since you are on linux would you able to check, if you are able to preview html with css links/images

**Comment by skandasoft** [comment]
Check the latest patch. Closing the issue. Feel free to open if problems still exist.

**Comment by olmokramer** [comment]
Works great over here! Awesome! Thank you for the quick fix :)
