### ISSUE TITLE
No available version compatible with the installed Atom version: 0.207.0

### ISSUE THREAD

**Issue by bvj** [skandasoft/preview-plus#31]
Unable to install

**Comment by abinashmeher999** [comment]
Same happens with 0.208.0 and 0.209.0

**Comment by antib0t** [comment]
seems like, there is an depricated API issue. Please fix it

**Comment by skandasoft** [comment]
Would try to get to this, in the weekend...

**Comment by brunoskonrad** [comment]
Nice @skandasoft! :+1: thanks

**Comment by skandasoft** [comment]
finally was able to get it done..Hopefully no more version breaking updates from ATOM...
Check the latest updates...Closing the issue..feel free to reopen/open new issues
