### ISSUE TITLE
Cursor doesn't return to source tab using LivePreview

### ISSUE THREAD

**Issue by usoliveira** [skandasoft/preview-plus#44]
When editing a coffee-script file at a left panel, using LivePreview to render it as JavaScript, the editor after every typed character, render the JavaScript (previewed view) but the cursos doens't returns back to source, even it is been setted at configuration file of preview-plus plugin.

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
