### ISSUE TITLE
Problems with keymaps

### ISSUE THREAD

**Issue by SduyXD** [skandasoft/preview-plus#5]
menus/preview-plus.cson
Use the `atom-text-editor` tag instead of the `editor` class.

keymaps/preview-plus.cson
Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by skandasoft** [comment]
I have few more things I will add. I will put along with that this one.

**Comment by skandasoft** [comment]
Check the latest patch. Closing the issue. Feel free to open if problems still exist.

**Comment by SduyXD** [comment]
Its Fixed Thanks + :star:
