### ISSUE TITLE
External CSS files are ignored in HTML preview

### ISSUE THREAD

**Issue by notargets** [skandasoft/preview-plus#6]
Linked CSS files have no effect when previewing an HTML file. I have tried it with selecting htmlp, with Atom 0.176.0 under GNU/Linux.

**Comment by skandasoft** [comment]
Did you maintain the base directory for the folder, which has these html/css files. To maintain the base directory type preview-plus:base in the command window. See if it that will be the directory that need to go before your linked css files. Please confirm if it works by updating the base directory for HTMLP.

**Comment by notargets** [comment]
Yes, the project folder containing the files is set correctly as the HTML base.

**Comment by skandasoft** [comment]
can you paste the code/screen shot of the screen.

**Comment by notargets** [comment]
Here is a screenshot:
![atom-editor-previewplus](https://cloud.githubusercontent.com/assets/10419911/6009958/1138e0f6-ab2f-11e4-946b-bc4508c12eca.png)

And [here] (http://www.mediafire.com/download/4ymp08y0f1bxvcn/myWebPage.zip) are the project files.

**Comment by skandasoft** [comment]
Can you try putting a slash at the end of the HTML Base and try it out

**Comment by skandasoft** [comment]
can you add under the <head> tag
```
<base href='/media/.../webPage/'></base>
```
with href pointing to the HTML Base and save it in desktop and open in chrome and see if it picks up the css.

**Comment by notargets** [comment]
It is still the same in both Chromium and Firefox, with everything appearing correctly, but within Atom and htmlp, it looks the same as in the screenshot.

**Comment by skandasoft** [comment]
so you saved the html file to desktop with the base tag added as I mentioned and opened the html file in desktop in chromium

**Comment by notargets** [comment]
Yes.

**Comment by skandasoft** [comment]
can you try going to config for preview plus and switching off the webview(it is switched on by default)

**Comment by notargets** [comment]
If I turn it off, this web page looks the same in the preview. However, it solves another issue in another project, namely UTF-8 character coding.

**Comment by notargets** [comment]
By the way, Atom says preview-plus makes 4 deprecated calls. I'm not sure if they are related to this problem.

**Comment by skandasoft** [comment]
I don't have the problem with windows..I don't have a way to debug it/look at what is missing. I am going to wait for some more feedbacks.

**Comment by skandasoft** [comment]
I went ahead and put a patch so you should be see the preview for html with the linked css. To enable this go to the setting for preview-plus package and switch on html url (click the checkbox). and reload.
The only issue would be that inline javascript will not execute with this approach. But you would still be able to use the selected text and preview it using the older approach..
Please check and close the issue if it works.

**Comment by notargets** [comment]
It seems to work now, thank you very much!
