### ISSUE TITLE
Looking for help/feedback with testing in Non windows OS

### ISSUE THREAD

**Issue by skandasoft** [skandasoft/preview-plus#7]
I have tested this package with windows 7. I am looking for feedback on the list of features available in this package using other OS. All contributions are welcome.

**Comment by fibric** [comment]
I am on OSX 10.10.3 (14D105g).

After manually installing `cd ~/.atom/packages/preview-plus/ && npm install event-kit` it works.
But it does not have a menu item. Preview Plus is accessible only via command palette. Its not bad by default (I like to use my keyboard), but I can imagine someone does like to use his mouse.

Performance is okay. Generated HTML code is shown with correct syntax theme. Indentation is the only thing left to complain about. The generated HTML code is flatly aligned on column 0.

The design of status bar entries is 'improvable'
![image](https://cloud.githubusercontent.com/assets/623932/6775133/ec811c28-d12c-11e4-811c-c64d29539625.png)

**Comment by skandasoft** [comment]
.I am not really artistic..pr welcome..
