### ISSUE TITLE
Live preview of an HTML file while a linked CSS file is being edited

### ISSUE THREAD

**Issue by notargets** [skandasoft/preview-plus#8]
I've just tried the latest version of your package under GNU/Linux, and I noticed that a preview of an HTML file can only be updated on change when that one is being edited. Is it possible to update it live also when a CSS file linked to it is being edited?

**Comment by skandasoft** [comment]
Please check the latest version..go check the preview-plus:base for the directory to be watched for the live preview...in your case you should add the stylesheet folder/*.css and then open the preview..also press f12 for chrom dev tools

**Comment by notargets** [comment]
I've tried upgrading to V 1.1.17, but I get an error message:

```
Installing preview-plus@1.1.17 to /home/xxx/.atom/packages ✗

npm ERR! Linux 3.18.3-1-MANJARO
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/xxx/.atom/.apmrc" "install" "/tmp/d-11518-5647-pzd9hs/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: chokidar@'>=1.0.0 <1.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-rc1","1.0.0-rc1.1","1.0.0-rc2","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","0.7.1","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.5","0.10.6","0.10.7","0.10.8","0.10.9","0.11.0","0.11.1","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.12.6","1.0.0-rc1","1.0.0-rc1.1","1.0.0-rc2","1.0.0-rc3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11518-5647-i2ufpe/npm-debug.log
```

Also, I cannot find the file npm-debug.log anywhere in /tmp.

**Comment by skandasoft** [comment]
check the latest patch

**Comment by notargets** [comment]
Now I could upgrade to V1.1.19, but it does not seem to be working at all. I cannot find buttons like Live and HTMLP on the status bar, commands related to preview-plus in the quick command (shift-ctrl-p) and ctrl-alt-o does not do anything any more.

**Comment by skandasoft** [comment]
Currently working on a slimmer version of the same..The next release would be atleast 3 weeks.

Could try uninstall and re install again.

**Comment by notargets** [comment]
I have already tried it and it would still not work.

**Comment by skandasoft** [comment]
Can you open the console to see if there is any message. Click on the menu path view-> developer tools

**Comment by skandasoft** [comment]
The latest patch would help. Please check and re open issues if it still exists
